# Data Columns
KEY_LISTING_NAME = "Listing Name"
KEY_REVPAR_INDEX = "RevPAR Index"
KEY_REVPAR_INDEX_STLY = "RevPAR Index STLY"
KEY_RENTAL_REVPAR = "Rental RevPAR"
KEY_RENTAL_REVPAR_STLY = "Rental RevPAR STLY"
KEY_MARKET_REVPAR = "Market RevPAR"
KEY_MARKET_REVPAR_STLY = "Market RevPAR STLY"
KEY_MARKET_PEN = "Market Penetration Index %"
KEY_MARKET_PEN_STLY = "Market Penetration Index STLY"
KEY_PAID_OCCUPANCY = "Paid Occupancy %"
KEY_PAID_OCCUPANCY_STLY = "Paid Occupancy % STLY"
KEY_MARKET_OCCUPANCY = "Market Occupancy %"
KEY_MARKET_OCCUPANCY_STLY = "Market Occupancy % STLY"
KEY_BOOKED_NIGHTS_PICKUP = "Booked Nights Pickup (30 Days)"
KEY_PAID_OCCUPANCY = "Paid Occupancy %"
KEY_PAID_OCCUPANCY_STLY = "Paid Occupancy % STLY"
KEY_TOTAL_REVENUE = "Total Revenue"
KEY_TOTAL_REVENUE_STLY = "Total Revenue STLY"

REQUIRED_COLUMNS = [
    KEY_LISTING_NAME, KEY_REVPAR_INDEX, KEY_REVPAR_INDEX_STLY,
    KEY_RENTAL_REVPAR, KEY_RENTAL_REVPAR_STLY, KEY_MARKET_REVPAR,
    KEY_MARKET_REVPAR_STLY, KEY_MARKET_PEN, KEY_MARKET_PEN_STLY,
    KEY_PAID_OCCUPANCY, KEY_PAID_OCCUPANCY_STLY, KEY_PAID_OCCUPANCY,
    KEY_PAID_OCCUPANCY_STLY, KEY_MARKET_OCCUPANCY, KEY_MARKET_OCCUPANCY_STLY,
    KEY_TOTAL_REVENUE, KEY_TOTAL_REVENUE_STLY, KEY_BOOKED_NIGHTS_PICKUP
]

# App Constants
KEY_LABELS = "Labels"
REPORT_WIDTH = 297
REPORT_HEIGHT = 210

customers = ["Pierce Gainey", "Austin Whitaker"]
